services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        NODE_ENV: development
      # Remove 'target' as it is not necessary
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    # Remove 'command' as it should be specified in the Dockerfile instead
    ports:
      - 3000:3000

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  redis:
